server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /gms

spring:
  application:
    name: gms
  
  datasource:
    url: jdbc:mysql://www.1016.cc:3306/gms?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: gmsdev
    password: Gms@)18
    driverClassName: com.mysql.cj.jdbc.Driver

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  quartz:
      #相关属性配置
      properties:
        org:
          quartz:
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
              tablePrefix: QRTZ_
#              isClustered: true
              clusterCheckinInterval: 10000
              useProperties: false
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
      #数据库方式
      job-store-type: jdbc
      #初始化表结构
      #jdbc:
        #initialize-schema: never

mybatis-plus:
  mapper-locations: classpath*:sqlmap/*Mapper.xml

redis:
  auth:
    host: www.1016.cc
    port: 6379
    timeout: 0
    password: Gms@)18Gms@)18

taoyuan:
  unAuthUrls:
    - /contentmgnt/announcement/**
  permissions:
    /sitemanage/account/**=perms["account:*"]

quartz:
  enabled: true