server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /gms
#
#logging:
#  level:
#    com.migu.tsg.pms.service: debug
    
#spring
spring:
  application:
    name: gms
  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.215.89:3306/gms?allowMultiQueries=true&amp
    username: gmsdev
    password: Gms@)18

mybatis:
  mapper-locations: classpath*:sqlmap/*Mapper.xml