# 注册管理员
POST https://localhost:8443/gms/users/createAdmin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{   "userName": "huawei2", "phone": "11111111111",   "password": "admin" }

###

# 登录
POST http://localhost:8081/gms/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{   "userName": "huawei2",   "password": "admin" }

###

# 分配代理
POST http://localhost:8081/gms/users/allocateProxy
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: b21f6cd9-54d6-4b7d-82ed-ddd8cf350fac

{   "name": "代理会员44",   "distribMoney": "500", "phone": "18594873899", "password": "proxy" }

###

# 注册会员
POST http://localhost:8081/gms/users/register
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: 2e0b20dc-ce83-4671-a9e9-376360ea9584

{   "refereeId": "2",   "verificationCode": "uy74", "smsVerificationCode": "6675", "nickName": "jack", "phone": "18794873892", "password": "proxy" }

###

# 管理员变更
POST http://localhost:8081/gms/users/updateAdmin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: 8de4fd88-3080-4cba-a8c8-f59ec70982cc

{  "id":18, "phone": "18898889998", "password": "admin2"  }

###

# 查询管理员
POST http://localhost:8081/gms/users/getAdmin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: 6ffc526f-ecd1-4c1d-947f-a07320ca5098

{  "pageIndex":1, "pageSize": "20"  }

###

# 代理变更
POST http://localhost:8081/gms/users/updateProxy
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: e86d0e26-974e-4971-bcb4-0213ed5fa6ef

{  "id":20, "name": "代理会员更新1", "phone": "15898888887"  }

###

# 会员变更
POST http://localhost:8081/gms/users/update
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: e86d0e26-974e-4971-bcb4-0213ed5fa6ef

{  "id":22, "name": "会员名称1", "phone": "15898888887", "qq": "837979234", "password": "guest11" }

###

# 管理员注销
POST http://localhost:8081/gms/users/delete/22
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: 8de4fd88-3080-4cba-a8c8-f59ec70982cc


###

# 性能监控
POST http://localhost:8081/actuator/env
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
token: 76f72b4e-042f-4843-be82-0d2660d32900


###

# 查询会员
POST http://localhost:8081/gms/users/get
Accept: */*
Content-Type: application/json
token: 0ddc3d24-fa6e-4d0f-88d6-0b7ec889f1ea

{
    "pageIndex":1,
    "pageSize":20,
    "queryKey":"17",
    "types":
    [0,1,2]
}

###
# 查询所有会员
POST http://localhost:8081/gms/users/get
Accept: */*
Content-Type: application/json
token: b4bf9275-0bf0-4ff7-84ee-0100e6cf8611

{
    "pageIndex":1,
    "pageSize":20
#   "queryKey":"17",
//    "types":
//    [0]
}

###
# 删除会员
POST http://localhost:8081/gms/users/delete/17
Accept: */*
Content-Type: application/json
token: 0ddc3d24-fa6e-4d0f-88d6-0b7ec889f1ea

###
