###图片上传，返回图片名称
POST http://localhost:8081/gms/sitemgnt/upload/image
Accept: */*
Content-Type: application/json
Token: 35355db7-6dd9-4aa7-91fc-f000e26713fb

{
  "file":选中的图片文件
}

###获取图片资源
http://localhost:8081/gms/img/上传返回的图片名称

###
